# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: demoCypress
on:
  push:
    branches:
      - 'master'

jobs:
  cypress-run:
    name : Run on Chrome 86
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.15.0-chrome86-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install cypress and verify
        run: |
          npm ci
          $(npm bin)/cypress verify
      - name: Run Cypress tests
        run : npm run test:chrome
        continue-on-error: false

      -name: Copy test execution videos and screenshot
        run : |
          mkdir public
          cp -r cypress/videos public/video
          cp -r cypress/screenshots public/screenshots

      -name: Merge test reports
       run: npm run combine:report

      -name: Generate HTML reports
      -run: npm run generate:report 
      -name: Deploy report page to GitHub Page


       uses: cypress-io/github-action@v2
       with:
         github_token: ${{ secrets.GITHUB_TOKEN}}
         publish_dir: ./public
