# This is a basic workflow to help you get started with Action

name: demoCypress
on:
  push:
    branches:
      - 'master'

jobs:
  cypress-run:
    name: Run on Chrome 83
    runs-on: ubuntu-18.04
    container: cypress/browsers:node14.15.0-chrome86-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install cypress and verify
        run: |
          npm ci
          $(npm bin)/cypress verify
      - name: Run Cypress tests
        run : npm run test:chrome
        continue-on-error: false

      - name: Copy test execution videos and screenshot
        run : |
          mkdir public
          cp -r cypress/videos public/video
          cp -r cypress/screenshots public/screenshots
      - name: Merge test reports
        run: npm run combine:report

      - name: Generate HTML reports
        run: npm run generate:report 
      - name: Deploy report page to GitHub Page


        uses: peaceiris/actions-gh-pages@v3
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./public
